oppdrag.mq:
  queuemanager: MQLS02
  send: QA.Q1_231.OB04_OPPDRAG_XML
  mottak: QA.Q1_FAMILIE_OPPDRAG.OPPDRAG_FAMILIE_XML_KVITT
  avstemming: QA.Q1_234.OB29_AVSTEMMING_XML
  tss: QA.Q1_415.AS10_SAMHANDLER_SERVICE
  channel: Q1_FAMILIE_OPPDRAG
  hostname: b27apvl220.preprod.local
  port: 1413
  user: ${SERVICEUSER_USERNAME}
  password: ${SERVICEUSER_PASSWORD}
  enabled: true



no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-oppdrag

OPPDRAG_SERVICE_URL: "https://cics-q1.adeo.no/oppdrag/simulerFpServiceWSBinding"
SECURITYTOKENSERVICE_URL: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
TILBAKEKREVING_V1_URL: https://cics-q1.adeo.no/oppdrag/K231CW80