oppdrag.mq:
  queuemanager: QM1
  send: DEV.QUEUE.1
  mottak: DEV.QUEUE.1
  avstemming: DEV.QUEUE.2
  tss: DEV.QUEUE.3
  channel: DEV.ADMIN.SVRCONN
  hostname: localhost
  port: ${OPPDRAG_MQ_PORT_OVERRIDE}
  user: admin
  password: passw0rd
  enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token

spring.datasource.url: ${SPRING_DATASOURCE_URL_OVERRIDE}
spring.datasource.username: ${SPRING_DATASOURCE_USERNAME_OVERRIDE}
spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD_OVERRIDE}
spring.datasource.driver-class-name: ${SPRING_DATASOURCE_DRIVER_OVERRIDE}

SECURITYTOKENSERVICE_URL: https://localhost:8063/soap/SecurityTokenServiceProvider/
SERVICEUSER_USERNAME: not-a-real-srvuser
SERVICEUSER_PASSWORD: not-a-real-pw
OPPDRAG_SERVICE_URL: #Mockes ut lokalt
AZURE_APP_WELL_KNOWN_URL: "https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration"